Fixes issue due to missing double quote
Error: Could not find template 'gitlab/unicorn.rb.${gitlab::gitlab_branch}.erb' at /etc/puppet/modules/gitlab/manifests/setup.pp:76 on node gitlab.localdomain
Error: Could not find template 'gitlab/unicorn.rb.${gitlab::gitlab_branch}.erb' at /etc/puppet/modules/gitlab/manifests/setup.pp:76 on node gitlab.localdomain